# Generated by Django 5.1.2 on 2025-07-11 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_journalentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=233)),
                ('answer', models.TextField()),
                ('topic', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
